title: Blog on ALL THE THINGS
author: pradeep
email: pradeep@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
# social links
twitter_username: pradeep
github_username: pradeep

show_excerpts: true # set to false to remove excerpts on the homepage

theme: Minima
